### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by HydroGames-dev** [alvin0319/AmongUs#11]
The Tip message doesn't go away
![20201111_200358](https://user-images.githubusercontent.com/69600115/98826873-3d5c9180-245c-11eb-946e-1127ced9b45b.jpg)

The map is purple
![Screenshot_20201111-194955_Toolbox](https://user-images.githubusercontent.com/69600115/98826984-5b29f680-245c-11eb-8c25-53f3ddc88a86.jpg)

**Comment by alvin0319** [comment]
God I hate Altay :(

**Comment by alvin0319** [comment]
https://github.com/alvin0319/AmongUs/blob/master/src/alvin0319/AmongUs/item/FilledMap.php#L72

**Comment by alvin0319** [comment]
closed in https://github.com/alvin0319/AmongUs/commit/c9d3096dd3147dafc26b2e48f6a82c5fba1e8624
