### ISSUE TITLE
Fatal error at use SingletonTrait; in AmongUs.php

### ISSUE THREAD

**Issue by kalsel1295** [alvin0319/AmongUs#14]

**Comment by alvin0319** [comment]
Please provide the error log

**Comment by alvin0319** [comment]
This will be resolved because PM3 implemented SingletonTrait (https://github.com/pmmp/PocketMine-MP/commit/8273f789ee785cda3269e3a9841e99241503dc4f)

**Comment by kalsel1295** [comment]
Fatal error in AmongUs.php in code use use SingletonTrait;
