### ISSUE TITLE
How to do Tasks works

### ISSUE THREAD

**Issue by ghost** [alvin0319/AmongUs#16]
Hello, I am new to this plugin and I just want to know the way tasks are functioned. I haven’t tryed the plugin yet but I just want know if the tasks require a item or you set up the tasks

**Comment by HydroGames-dev** [comment]
Tasks are not yet done

**Comment by ghost** [comment]
Oh that makes sense so it not tested or used?

**Comment by HydroGames-dev** [comment]
It's not yet use able
There are tasks (not completely working)
but you can't do them like no way to use the task

**Comment by ghost** [comment]
Oh ok.
