### ISSUE TITLE
Give me plugin kim\present\converter\png\PngConverter; pls

### ISSUE THREAD

**Issue by kalsel1295** [alvin0319/AmongUs#22]

**Comment by alvin0319** [comment]
PngConverter is not a plugin, and this plugin is not completed.

use [DEVirion](https://github.com/poggit/devirion) and download [InvMenu](https://github.com/Muqsit/InvMenu), [png-converter](https://github.com/PresentKim/png-converter), and [array-utils](https://github.com/PresentKim/array-utils).

**Comment by kalsel1295** [comment]
Thanks :)
