### ISSUE TITLE
Suggest

### ISSUE THREAD

**Issue by kalsel1295** [alvin0319/AmongUs#23]
Pls adding time in download data and adding sabootage 👍, and pls give me map example for test this plugin pls...

**Comment by HydroGames-dev** [comment]
[world.zip](https://github.com/alvin0319/AmongUs/files/5610229/world.zip)

The AmongUs Skeld map for Minecraft Pocket Edition

**Comment by kalsel1295** [comment]
Why build Navigation room error?
