### ISSUE TITLE
Why png-converter not working

### ISSUE THREAD

**Issue by kalsel1295** [alvin0319/AmongUs#24]
he said on the console there was an error in the Image converter plugin

**Comment by alvin0319** [comment]
why you didn't write anything?

**Comment by kalsel1295** [comment]
image converter plugin error said on the console on line 56, Said in the console: error: undefined function (EXEPTION) kim / present / converter / png / PngConverter on line 56

**Comment by kalsel1295** [comment]
![Uploading Screenshot_20201128-183743_PocketMine-MP.jpg…]()

**Comment by alvin0319** [comment]
make sure to enable GD extension.

**Comment by kalsel1295** [comment]
ok
